import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "../store/providers";
import AuthProvider from "@/lib/utils/authProvider";
import { Toaster } from "react-hot-toast";
import CloudinaryProvider from "@/lib/utils/cloudinaryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Kas Tok Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <CloudinaryProvider>
          <AuthProvider>
            <Providers>{children}</Providers>
          </AuthProvider>
        </CloudinaryProvider>
      </body>
    </html>
  );
}
